### ISSUE TITLE
Source downloads are corrupted

### ISSUE THREAD

**Issue by ah450** [ah450/runner-frontend#2]

**Comment by amrdraz** [comment]
can you elaborate :D

*Amr Draz*
*Teaching Assistant German University in Cairo (GUC)*

*Mobile:* (+2) (01001132292)   |   *LinkedIn: *[Profile
<http://eg.linkedin.com/in/amrdraz>] | *Skype: * (bing91)

**Comment by ah450** [comment]
@amrdraz 
Relevant code is in services.js Page service, download Handler. Around line 25.
Content-Length is 367, data.length in response is 360.
