### ISSUE TITLE
the system is down!!!!

### ISSUE THREAD

**Issue by youssefhafez** [ah450/runner-frontend#4]
![error1](https://cloud.githubusercontent.com/assets/11260591/6500439/4d749f5e-c314-11e4-8497-f7cae219eded.png)

yesterday was
![mile stone screen shot](https://cloud.githubusercontent.com/assets/11260591/6500441/4f85c94e-c314-11e4-8bc6-9b86ede3429b.jpg)

**Comment by amrdraz** [comment]
We know, we where the ones who stopped everything

There was an issue which required we charge how submissions are stored, and
we had to do it while still accepting submissions.

So we stopped submissions from running

Its funny cause we where seeing submissions passing and people still
submitting.

Thank you for reporting tho

**Comment by ah450** [comment]
@youssefhafez  The submissions are safe and sound. 
Feel free to resubmit to see the green icon. 
Soon old ones will show as they did previously. 
Sorry for the inconvenience.
